# Generated by Django 2.2.3 on 2020-03-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('Image1', models.ImageField(blank=True, upload_to='')),
                ('Image2', models.ImageField(blank=True, upload_to='')),
                ('Image3', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='myshop.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now=True)),
                ('productreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.Product')),
            ],
            options={
                'verbose_name': 'Product_Review',
                'verbose_name_plural': 'Product_Reviews',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.FloatField(default=0.0)),
                ('Length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('Materials', models.CharField(max_length=150)),
                ('Colors', models.CharField(max_length=150)),
                ('Sizes', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now=True)),
                ('productInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.Product', unique=True)),
            ],
            options={
                'verbose_name': 'Product_Info',
                'verbose_name_plural': 'Product_Infos',
                'ordering': ('-created',),
            },
        ),
    ]
