# Generated by Django 2.2.3 on 2020-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'ShippingCountry',
                'verbose_name_plural': 'ShippingCountries',
                'ordering': ('country',),
            },
        ),
    ]
