# Generated by Django 2.2.3 on 2020-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
